; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Wed Sep 30 2020 19:55:47 GMT+1300 (New Zealand Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


