; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Wed Sep 30 2020 19:55:50 GMT+1300 (New Zealand Daylight Time)

G91 ; relative positioning

M913 Z60                  ; drop motor current to 70%

G1 H1 Z115 F3000          ; Return build plate to bottom 
G1 Y100 F3000             ; More print bed to front for easier access

M913 Z100                 ; Return motor current to 100%
